// === CONSTANTS MODULE ===
// 애플리케이션에서 사용되는 모든 상수들을 정의합니다.

export const CONSTANTS = {
    SUBJECTS: {
        MUSIC: 'music',
        ART: 'art',
        KOREAN: 'korean',
        KOREAN_MODEL: 'korean-model',
        KOREAN_STD: 'korean-std',
        LIFE: 'life',
        LIFE_ACHIEVEMENT: 'life-achievement',
        WISE: 'wise',
        WISE_ACHIEVEMENT: 'wise-achievement',
        JOY: 'joy',
        JOY_ACHIEVEMENT: 'joy-achievement',
        PE: 'pe',
        PE_LITE: 'pe-lite',
        PE_MODEL: 'pe-model',
        INTEGRATED_MODEL: 'integrated-model',
        ART_MODEL: 'art-model',
        ART_BASIC: 'art-basic',
        ENGLISH: 'english',
        EASTERN_ETHICS: 'eastern-ethics',
        WESTERN_ETHICS: 'western-ethics',
        MORAL_PSYCHOLOGY: 'moral-psychology',
        ETHICS: 'ethics',
        ETHICS_LITE: 'ethics-lite',
        PRACTICAL: 'practical',
        PRACTICAL_LITE: 'practical-lite',
        MATH_MODEL: 'math-model',
        SOCIAL: 'social',
        SOCIAL_34: 'social-34',
        SOCIAL_56: 'social-56',
        SCIENCE: 'science',
        SCIENCE_CURRICULUM: 'science-curriculum',
        SCIENCE_STD: 'science-std',
        ENGLISH_STD: 'english-std',
        PRACTICAL_STD: 'practical-std',
        ART_STD: 'art-std',
        MATH_OPERATION: 'math-operation',
        CHANGE_RELATION: 'change-relation',
        GEOMETRY_MEASURE: 'geometry-measure',
        DATA_PROBABILITY: 'data-probability',

        CREATIVE: 'creative',
        OVERVIEW: 'overview',
        KOREAN_COURSE: 'korean-course',
        ENGLISH_COURSE: 'english-course',
        INTEGRATED_COURSE: 'integrated-course',
        SOCIAL_COURSE: 'social-course',
        MATH_COURSE: 'math-course',
        SCIENCE_COURSE: 'science-course',
        PRACTICAL_COURSE: 'practical-course',
        MUSIC_COURSE: 'music-course',
        ART_COURSE: 'art-course',
        PE_BACK: 'pe-back',
        PE_COURSE: 'pe-course',
        MORAL_COURSE: 'moral-course',
        MORAL_PRINCIPLES: 'moral-principles',
        MUSIC_ELEMENTS: 'music-elements',
        PHYSICAL_ACTIVITY: 'physical-activity',
        SPELLING: 'spelling',
        GEOMETRY: 'geometry',
        COMPETENCY: 'competency',
        AREA: 'area',
        INTEGRATED_GUIDE: 'integrated-guide',
        RANDOM: 'random',
    },
    TOPICS: {
        CURRICULUM: 'curriculum',
        COMPETENCY: 'competency',
        AREA: 'area',
        MODEL: 'model',
        COURSE: 'course',
        BASIC: 'basic',
        ACHIEVEMENT: 'achievement',
        MORAL: 'moral',
    },
    MODES: {
        NORMAL: 'normal',
        HARD_CORE: 'hard-core',
    },
    CSS_CLASSES: {
        HIDDEN: 'hidden',
        CORRECT: 'correct',
        INCORRECT: 'incorrect',
        RETRYING: 'retrying',
        REVEALED: 'revealed',
        SELECTED: 'selected',
        IS_SELECTING: 'is-selecting',
        ACTIVE: 'active',
        COMBO_POP: 'combo-pop',
        SHAKE: 'shake',
        CORRECT_PULSE: 'correct-pulse',
    },
    DEFAULT_DURATION: 2400,
    HARD_CORE_DURATION: 60,
    HARD_CORE_TIME_BONUS: 5,
    RANDOM_ANIMATION_DURATION: 2000,
    RANDOM_ANIMATION_INTERVAL: 100,
    STAGE_CLEAR_DURATION: 300,
    NEXT_STAGE_DELAY: 550,
};

export const SUBJECT_NAMES = {
    [CONSTANTS.SUBJECTS.MUSIC]: '음악',
    [CONSTANTS.SUBJECTS.ART]: '미술',
    [CONSTANTS.SUBJECTS.KOREAN]: '국어',
    [CONSTANTS.SUBJECTS.KOREAN_MODEL]: '국어',
    [CONSTANTS.SUBJECTS.KOREAN_STD]: '국어',
    [CONSTANTS.SUBJECTS.LIFE]: '바생',
    [CONSTANTS.SUBJECTS.LIFE_ACHIEVEMENT]: '바른 생활·슬기로운 생활',
    [CONSTANTS.SUBJECTS.WISE]: '슬생',
    [CONSTANTS.SUBJECTS.WISE_ACHIEVEMENT]: '건강한 생활',
    [CONSTANTS.SUBJECTS.JOY]: '즐생',
    [CONSTANTS.SUBJECTS.JOY_ACHIEVEMENT]: '즐거운 생활',
    [CONSTANTS.SUBJECTS.PE]: '체육',
    [CONSTANTS.SUBJECTS.PE_LITE]: '체육(lite)',
    [CONSTANTS.SUBJECTS.PE_MODEL]: '체육',
    [CONSTANTS.SUBJECTS.INTEGRATED_MODEL]: '통합',
    [CONSTANTS.SUBJECTS.ART_MODEL]: '미술',
    [CONSTANTS.SUBJECTS.ART_BASIC]: '미술',
    [CONSTANTS.SUBJECTS.ENGLISH]: '영어',
    [CONSTANTS.SUBJECTS.EASTERN_ETHICS]: '동양윤리',
    [CONSTANTS.SUBJECTS.WESTERN_ETHICS]: '서양윤리',
    [CONSTANTS.SUBJECTS.MORAL_PSYCHOLOGY]: '도덕 심리학',
    [CONSTANTS.SUBJECTS.ETHICS]: '도덕',
    [CONSTANTS.SUBJECTS.ETHICS_LITE]: '도덕(lite)',
    [CONSTANTS.SUBJECTS.PRACTICAL]: '실과',
    [CONSTANTS.SUBJECTS.PRACTICAL_LITE]: '실과(lite)',
    [CONSTANTS.SUBJECTS.MATH_MODEL]: '수학',
    [CONSTANTS.SUBJECTS.SOCIAL]: '사회',
    [CONSTANTS.SUBJECTS.SOCIAL_34]: '사회34',
    [CONSTANTS.SUBJECTS.SOCIAL_56]: '사회56',
    [CONSTANTS.SUBJECTS.SCIENCE]: '과학',
    [CONSTANTS.SUBJECTS.SCIENCE_CURRICULUM]: '과학',
    [CONSTANTS.SUBJECTS.SCIENCE_STD]: '과학',
    [CONSTANTS.SUBJECTS.ENGLISH_STD]: '영어',
    [CONSTANTS.SUBJECTS.PRACTICAL_STD]: '실과',
    [CONSTANTS.SUBJECTS.ART_STD]: '미술',
    [CONSTANTS.SUBJECTS.MATH_OPERATION]: '수와 연산',
    [CONSTANTS.SUBJECTS.CHANGE_RELATION]: '변화와 관계',
    [CONSTANTS.SUBJECTS.GEOMETRY_MEASURE]: '도형과 측정',
    [CONSTANTS.SUBJECTS.DATA_PROBABILITY]: '자료와 가능성',

    [CONSTANTS.SUBJECTS.CREATIVE]: '창체',
    [CONSTANTS.SUBJECTS.OVERVIEW]: '총론',
    [CONSTANTS.SUBJECTS.KOREAN_COURSE]: '국어',
    [CONSTANTS.SUBJECTS.ENGLISH_COURSE]: '영어',
    [CONSTANTS.SUBJECTS.INTEGRATED_COURSE]: '통합',
    [CONSTANTS.SUBJECTS.SOCIAL_COURSE]: '사회',
    [CONSTANTS.SUBJECTS.MATH_COURSE]: '수학',
    [CONSTANTS.SUBJECTS.SCIENCE_COURSE]: '과학',
    [CONSTANTS.SUBJECTS.PRACTICAL_COURSE]: '실과',
    [CONSTANTS.SUBJECTS.MUSIC_COURSE]: '음악',
    [CONSTANTS.SUBJECTS.PE_COURSE]: '체육',
    [CONSTANTS.SUBJECTS.MORAL_COURSE]: '도덕',
    [CONSTANTS.SUBJECTS.MORAL_PRINCIPLES]: '원리와 방법',
    [CONSTANTS.SUBJECTS.PE_BACK]: '체육(뒷교)',
    [CONSTANTS.SUBJECTS.MUSIC_ELEMENTS]: '음악요소',
    [CONSTANTS.SUBJECTS.PHYSICAL_ACTIVITY]: '신체활동 예시',
    [CONSTANTS.SUBJECTS.SPELLING]: '맞춤법',
    [CONSTANTS.SUBJECTS.GEOMETRY]: '도형',
    [CONSTANTS.SUBJECTS.COMPETENCY]: '역량',
    [CONSTANTS.SUBJECTS.AREA]: '영역',
    [CONSTANTS.SUBJECTS.INTEGRATED_GUIDE]: '통합 지도서',
};

export const TOPIC_NAMES = {
    [CONSTANTS.TOPICS.CURRICULUM]: '내체표',
    [CONSTANTS.TOPICS.COMPETENCY]: '역량',
    [CONSTANTS.TOPICS.AREA]: '영역',
    [CONSTANTS.TOPICS.MODEL]: '모형',
    [CONSTANTS.TOPICS.COURSE]: '교육과정',
    [CONSTANTS.TOPICS.BASIC]: '기본이론',
    [CONSTANTS.TOPICS.ACHIEVEMENT]: '성취기준',
    [CONSTANTS.TOPICS.MORAL]: '기타',
};
